### ISSUE TITLE
Window in Update Manager not themed

### ISSUE THREAD

**Issue by Shashank-Salian** [B00merang-Project/macOS-Catalina-Dark#1]
In Update Manager, refresh updates window is not dark in theme.
![Screenshot from 2020-08-04 22-16-07](https://user-images.githubusercontent.com/48306111/89322225-8fde2300-d6a1-11ea-8fcd-8425d236769f.png)
Well... Thank You for the fantastic theme.

**Comment by Elbullazul** [comment]
Applications launched with root privileges will fail to load the theme if not installed globally. Try copying the theme folder in /usr/share/themes
